### ISSUE TITLE
[feat] 自动激活签到获得的1G流量日包

### ISSUE THREAD

**Issue by auto-bot-ty** [srcrs/unicom-task#19]
能否自动激活签到获得的1G流量日包,感谢大佬!

**Comment by srcrs** [comment]
> 能否自动激活签到获得的1G流量日包,感谢大佬!

没有这个活动了吧

**Comment by auto-bot-ty** [comment]
> > 能否自动激活签到获得的1G流量日包,感谢大佬!
> 
> 没有这个活动了吧

安徽地区还是有的，签到会送1G流量日包，我用[这个脚本](https://github.com/mixool/HiCnUnicom/blob/e2d3f9bdd12424e84c43fcb18a3d2545579672fa/CnUnicom.sh#L33)是可以激活
